---
- hosts: proxy
  remote_user: '{{ user }}'
  tasks:
    #- name: Test to ping to remote hosts from the localhost.
    #  ping:
    #  register: result
    #  when: ansible_hostname == "prd-client1"
    #  when: ansible_local.ansible.deploy.ver == "1.16"
    #  when: ansible_local.ansible.deploy.ver == "1.16" and (ansible_local.ansible.deploy.env == "PROD")
    #- name: Show debug message
    #  debug:
    #    msg: "{{ result }}"
    #- name: All hosts run this task.
    #  shell: hostname
    #  register: info
    #- name: The hostname included 'stg' skipped run this task.
    #  debug: 'msg="{{ ansible_fqdn }}"'
    #  when: info.stdout.find('stg')
    - name: Test to ping to remote host.
      ### If fact data has saving on ansible master host and variable 'ansible_hostname' included 'stg' character string then skipped run this task.
      ping:
      register: result
    - name: Show debug message
      debug:
         msg: "{{ result }}"
