---
#- name: Check necessary initial setting and package installation.
#  command: '{{ item }}'
#  with_items:
#    - "{{ selinux_check }}"
#    - '{{ ntpd_check }}'
#    - '{{ ntpdate_check }}'
#  register: check_result
# ignore_errors: True 
#- name: Updating apt repository
#  apt:
#    update_cache: yes
#  register: update
#  when: ansible_distribution == 'something' ## This 'When' is used to disabled executing this task.
- name: Task 1. groups variable on the top [group_vars].
  debug: msg="Task 1 -- {{ group_vars_ubuntu }}"
- name: Task 2. groups variable on the top [group_vars].
  debug: msg="Task 2 -- {{ group_vars_freebsd }}"
- name: Task 3. role level variable in [defaults].
  debug: msg="Task 3 -- {{ standard_defaults_main }}"
- name: Task 4. role level variable in [standard_vars].
  debug: msg="Task 4 -- {{ standard_vars_main }}"
- name: Task 5. Include vars file it storing at <role>_vars.
  include_vars: external.yml
  tags:
    - template
#- name: Task 5-1. role level variable in [standard_vars].
#  debug: msg="Task 5 -- {{ standard_vars_external }}"
- name: Task 6. Test template result.
  template: src=/Users/cain_chen/Ansible_dev/Project/DCS-SS/roles/standard/templates/ubuntu.conf.j2 dest=/tmp/ubuntu.conf backup=yes
  tags:
    - template
- name: Task 6-1. Show template on client.
  shell: cat /tmp/ubuntu.conf
  register: shell_result
  tags:
    - template
- name: Task 6-2. Show debug for Task 6-1.
  debug: msg="{{ shell_result.stdout_lines }}"
  tags:
    - template
