# This Ansible play-book file is used for creating the account to the selected destination Linux OS host.
---
- hosts: '{{ hosts }}'
  gather_facts: false
  remote_user: '{{ user }}'
  become: true
  vars:
    group_vars: abc
  tasks:
  - name: Check specified a group [{{ group_vars }}] has existed in target host.
    command: bash -c "cat /etc/group | grep -w '{{ group_vars }}'"
    register: group_result
    ignore_errors: true
  - name: Create a group [{{ group_vars }}] to the target host.
    group:
      name: "{{ group_vars }}"
      state: present
    when: group_result.stdout == ""
  - name: Grant [{{ group_vars }}] to have the passwordless promotion to sudo privileges.
    lineinfile:
      dest: /etc/sudoers
      state: present
      line: '%{{ group_vars }} ALL=(ALL:ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
  - name: Add user to target host.
    user: name={{ item }} state=present groups={{ item }} groups={{group_vars }} shell=/bin/bash comment="Created via Ansible by Cain.Chen"
    register: user_result
    with_items:
      - stop
  - name: Add public key for the new created account.
    authorized_key: user={{ item }} key={{ lookup('file', '/Users/cainchen/Ansible/ssh_key/{{ item }}') }}
    ignore_errors: true
    with_items:
      - stop
  - name: Debug - Print debug message.
    debug:
      msg: "{{ group_result }},{{ user_result }}"
  - name: Send notification message via Slack
    slack:
      token: <Replaced to your slack token at here>
      msg: "{{ inventory_hostname }} {{ group_result | to_nice_json }} {{ user_result | to_nice_json }}"
      color: good
      channel: #ansible
      icon_url: https://techblog.recochoku.jp/2808/Ansible-e1500023954352.png
