---
- hosts: '{{ hosts }}'
  gather_facts: false
  remote_user: '{{ user }}'
  become: true
  tasks:
  - name: Updating target host apt repository
    command: 'apt-get update -y'
    register: update
  - name: Send notification message via Slack
    slack:
      token: <Replaced to your slack token at here>
      msg: '{{hosts}} {{ update.stdout }} {{ update.stderr }}'
      color: good
      channel: #ansible
      icon_url: https://techblog.recochoku.jp/2808/Ansible-e1500023954352.png
