# This Ansible play-book is used to deploy WordPress site based on the Docker container.
---
- hosts: '{{ hosts }}'
  gather_facts: false
  remote_user: user1
  become: yes
  tasks:
  - name: Phase 1. Copy deploy source files to the target host
    copy:
      src: ./{{item}}
      dest: /opt/
      mode: 0755
      force: yes
    with_items:
      - docker-compose.yml
      - "{{ hosts }}/wordpress.sql"
      - "{{ hosts }}/wp.tar"
  - name: Phase 2. Start WordPress container
    command:
       docker-compose -f /opt/docker-compose.yml up -d
    register: result
  - name: Phase 3. Updating.
    unarchive:
      src: /opt/wp.tar
      dest: /var/www/
      remote_src: yes
  - name: Debug - Print debug message
    debug:
      msg: "{{ result }}"
