---
- hosts: localhost
  gather_facts: no
  remote_user: '{{ user }}'
  become: true
  tasks:
  - name: Ping test
    command: 'ping {{ hosts }} -c 1'
    register: ping
    ignore_errors: True
  - name: Send notification message via Slack
    slack:
      token: <Replaced to your slack token at here>
      msg: '{{ ping.stdout }} {{ ping.stderr }}'
      color: good
      channel: #ansible
      icon_url: https://techblog.recochoku.jp/2808/Ansible-e1500023954352.png
