---
- hosts: '{{ hosts }}'
  gather_facts: false
  remote_user: '{{ user }}'
  tasks:
    - name: Test to ping to remote hosts from the localhost.
      ping:
      register: result
    - name: Show debug message
      debug:
        msg: "{{ result }}"
