---
- hosts: localhost
  tasks:
  - name: Getting machine uptime
    command: 'uptime'
    register: uptime
  - name: Send notification message via Slack
    slack:
      token: <Replaced to your slack token at here>
      msg: 'Hi, I am {{ inventory_hostname }} {{ uptime.stdout }}!'
      color: good
      channel: #ansible
      icon_url: https://techblog.recochoku.jp/2808/Ansible-e1500023954352.png
